### ISSUE TITLE
Need changes for better browser support

### ISSUE THREAD

**Issue by dvdzkwsk** [TechnologyAdvice/local-sync#2]
## Compatibility
- [x] Fix naive `localStorage` object access. We need to verify that `localStorage` exists on the window before calling methods on it. Right now there are a bunch of `storage*` helpers that access `localStorage` without any compatibility checks or try/catches.
- [x] Replace usage of Object.assign.
- [x] Replace usage of spread operator for safety.
## Usage
- [x] Need to be able to read and write non-JSON values.
## Testing
- [ ] Add browser tests

**Comment by levithomason** [comment]
Let's add browser tests to that list, we have 0 tests atm.

**Comment by dvdzkwsk** [comment]
@levithomason added.

**Comment by levithomason** [comment]
Usage is already covered.  All methods are compatible with any JSON serializable value.

From the README.md https://github.com/TechnologyAdvice/local-sync#set-get-put:

### set, get, put

Use any JSON serializable data type.

``` js
ls.set('bob', {name: 'SpongeBob'})
ls.get('bob')
// => {name: 'SpongeBob'}

ls.set('quotes', ['Squidward!'])
ls.get('quotes')
// => ['Squidward!]
```

Update stored objects and arrays.

``` js
ls.put('bob', {address: '124 Conch Street'})
// => {name: 'SpongeBob', address: '124 Conch Street'}

ls.put('quotes', ['Why so crabby, Patty?'])
// => ['Squidward!', 'Why so crabby, Patty?']
```

**Comment by levithomason** [comment]
## Compatibility

> Fix naive `localStorage` object access. We need to verify that `localStorage` exists on the window before calling methods on it. Right now there are a bunch of `storage*` helpers that access `localStorage` without any compatibility checks or try/catches.

I think should go with an in-memory option here for simplicity out of the gate.  I'll make a PR.

> Replace usage of Object.assign.

Done, #4.

> Replace usage of spread operator for safety.

This is not necessary as the library is babel compiled.  We could remove it from the one usage of arg spread, however, we'd have to rewrite the babel `_extend` helper if we removed spread altogether.

### Usage

> Need to be able to read and write non-JSON values.

This has always been possible (see above).  We accept reading and writing several types and every call to storage validates values before proceeding.  See `_validateValue()`:

``` js
const validTypes = [null, undefined, true, 0, '', [], {}]
```

## Testing

> Add browser tests

Agreed, I added CircleCI and Codecov with badges for reminder help.  Will continue moving us this way.

**Comment by levithomason** [comment]
Closing for housekeeping.  I don't think the final item here is going to get the attention it needs due to lack of time and funds.  We can open a specific issue to address it later if need be.
